export const CURRENCY_SYMBOL = '£';
export const CURRENCY_CODE = 'GBP';

export const ROUTES = {
  HOME: '/',
  SHOP: '/shop',
  SHOP_CATEGORY: '/shop/:category',
  PRODUCT_DETAILS: '/product/:slug',
  BRANDS: '/brands',
  BRAND_DETAILS: '/brands/:slug',
  RECIPES: '/recipes',
  ALL_CUISINES: '/recipes/cuisines',
  BLOG: '/blog',
  BLOG_DETAILS: '/blog/:slug',
  ABOUT: '/about',
  CONTACT: '/contact',
  WISHLIST: '/wishlist',
  CART: '/cart',
  CHECKOUT: '/checkout',
  TRACK_ORDER: '/track-order',
  LOGIN: '/login',
  REGISTER: '/register',
  FORGOT_PASSWORD: '/forgot-password',
  ORDERS: '/orders',
  ORDER_DETAILS: '/orders/:id',
  PROFILE: '/profile',
  ADDRESSES: '/addresses',
  SEARCH: '/search',
  CHANGE_PASSWORD: '/change-password',
  NOTIFICATIONS: '/notifications',
  SUPPORT: '/support',
  REWARDS: '/rewards',
  COMING_SOON: '/coming-soon',
};
